import Head from "next/head";
import Image from "next/image";
import { Inter, Lateef } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Layout from "@/components/Layout";
import profilePic from "../../public/images/profile/developer-pic-1.png";
import AnimatedText from "@/components/AnimatedText";
const inter = Inter({ subsets: ["latin"] });
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import HireMe from "@/components/HireMe";
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";
import TranstionEffect from "@/components/TranstionEffect";
export default function Home() {
  return (
    <>
      <Head>
        <title>Hossam Fahmy</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TranstionEffect />
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout className="pt-0 md:p-16 sm:pt-8 ">
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-1/2 md:w-full">
              <Image
                src={profilePic}
                alt="Hossam Fahmy"
                className="w-full h-auto sm:hidden md:inline-block md:w-full"
                property
                sizes="(max-width:768)100vw,
                (max-width:1200px)50vw,
              50vw
                "
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
              <AnimatedText
                text="Turning Vision Into Reality With Code And Design."
                className="!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl"
              />
              <p className="my-4 text-base font-medium md:text-sm sm:text-xs ">
                As a skilled full-stack developer, I am dedicated to turning
                ideas into innovative web applications. Explore my latest
                projects and articles, showcasing my expertise in React.js and
                web development.
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center z-30">
                <Link
                  href="/hossamfahmy.pdf"
                  target="_blank"
                  className="dark:bg-light dark:text-dark flex items-center bg-dark text-light p-2.5 px-6 rounded-full text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark  hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:p-2 md:px-4 md:text-base "
                  download={true}
                >
                  Resume
                  <LinkArrow className={"w-6 ml-1"} />
                </Link>
                <Link
                  href="mailto:hossameldinfahmi@gmail.com"
                  className="ml-5 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base "
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div className="absolute right-8 inline-block w-24 bottom-7 md:hidden">
          <Image src={lightBulb} alt="Hossam" className="w-full h-auto" />
        </div>
      </main>
    </>
  );
}
